HashMap for first review
NevMem/HashMap pull request #1
Opened 2019-03-09 16:46 UTC by NevMem

2019-03-10 13:46 UTC, Skird requested changes

2019-03-10 13:46 UTC, Skird commented on HashMap.h
> +    bool __need_rehash() const {
Никогда не надо использовать __ в своих идентификаторах
https://en.cppreference.com/w/cpp/language/identifiers
"the identifiers with a double underscore anywhere are reserved"

2019-03-10 13:46 UTC, Skird commented on HashMap.h
> +    class iterator {
Очень много кода продублировано для двух итераторов, надо подумать, как унифицировать

2019-03-10 13:46 UTC, Skird commented on HashMap.h
> +     friend class HashMap<KeyType, ValueType, Hasher>;
как-то некрасиво с friend, циклические зависимости, HashMap знает о структуре своих итераторов и наоборот. Подобных паттернов лучше избегать. Например, можно после конструирования всегда делать __iterate_forward() если надо, чтобы вообще нельзя было получить плохой итератор

2019-03-10 13:46 UTC, Skird commented on HashMap.h
> +        insert(std::pair<KeyType, ValueType>(key, ValueType()));
__insert зачем-то возвращает bool, который никто вроде не использует
А мог бы возвращать индекс и не пришлось бы делать лишний find

2019-03-10 13:50 UTC, Skird commented on HashMap.h
> +#include <stdexcept>
Всегда надо использовать include guards или хотя бы на худой конец #pragma once
Иначе этот файл будет очень больно включать
Дополнительно, всегда стоит использовать namespace, иначе засоряется глобальный и может быть проблемы с конфликтами при линковке

2019-03-10 13:55 UTC, Skird commented on HashMap.h
> +            size_t indexToInsert = keyHash % destination.size();
Кстати эта пара строк частенько повторяется - отличный повод вынести в функцию. Бонус: легко будет менять политику хеширования

2019-03-10 13:56 UTC, Skird commented on HashMap.h
> +    HashMap(Hasher hasher = Hasher()): capacity(0), presentSize(0), filled(0), hasher(hasher) {}
Конструктор от одного аргумента всегда (за очень редким исключением) стоит делать explicit
А если не делать, то лучше оставить комментарий, зачем так сделано и пометить вообще как
/* implicit */ HashMap(...)

2019-03-10 14:04 UTC, Skird commented on HashMap.h
> +    template <typename Iter>
Хороший тон - указывать в typename, с каким итератором готова работать структура

2019-03-10 20:23 UTC, NevMem commented
Переписал все, кроме, возвращения bool из insert'а, потому, что использую этот бул для того, чтобы понимать, над ли увеличивать presentSize в функции insert_, т. е. я помучаю уделенные как removed и если добаляется элемент с тем же ключом, что и когда то ранее, то мне надо знать правда ли, что этот элемент был действительно добавлен(так как insert по условию не вставляет элемент если была добавлена пара с тем же ключом)

2019-03-24 16:01 UTC, Skird requested changes
Все красиво, осталась пара деталей

2019-03-24 16:01 UTC, Skird commented on HashMap.h
> +        HashMap(ForwardIterator begin, ForwardIterator end, Hasher hasher = Hasher()):
Достаточно на самом деле InputIterator

2019-03-24 16:01 UTC, Skird commented on HashMap.h
> +        void erase(const KeyType& key) {
Последнее замечание: неплохо было бы освобождать память при удалении, чтобы не большой таблицы под пару элементов. Тут 2 варианта
1) сделать автоматический rehash если size * 8 < capacity или что-то такое
2) сделать как у std::vector, память он не освобождает, но у него хотя бы есть метод shrink_to_fit для ручного контроля размера

2019-03-27 20:26 UTC, Skird approved these changes

2019-03-27 20:26 UTC, merged